# Source: https://defn.io/2020/05/05/github-actions-for-racket-revised/

name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.6.1
        with:
          architecture: "x64"
          distribution: "full"
          version: "8.2"

      - name: Install Package and its Dependencies
        run: |
          cd src/exercises/github-actions-for-racket
          raco pkg install --auto --batch

      - name: Run Tests
        run: |
          cd src/exercises/github-actions-for-racket
          raco test fibonacci.rkt
